#infra_region = ""
#infra_tf_state_s3_bucket = ""
infra_tf_state_s3_key = "semantic-search/terraform.tfstate"
docs_src = "amazon-eks-user-guide"  #select the repo to be ingested like "amazon-eks-user-guide"
script_name = "run_ingestion_awsdocs"